"""Build the maintained-page Font Awesome CSS and WOFF2 subsets.

Install the pinned inputs first:
  npm ci
  python -m pip install -r requirements-fonts.txt

Then run this file directly or through the npm scripts. The --check mode builds
into a temporary directory and requires byte-for-byte equality with the tracked
assets, including the generated manifest.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
import sys
import tempfile
import xml.etree.ElementTree as ET
from pathlib import Path
from urllib.parse import urlparse

from fontTools import __version__ as fonttools_version
from fontTools import subset
from fontTools.ttLib import TTFont


ROOT = Path(__file__).resolve().parents[1]
PACKAGE_ROOT = ROOT / "node_modules" / "@fortawesome" / "fontawesome-free"
PACKAGE_JSON = PACKAGE_ROOT / "package.json"
SOURCE_CSS = PACKAGE_ROOT / "css" / "all.min.css"
SOURCE_BRANDS_CSS = PACKAGE_ROOT / "css" / "brands.min.css"
SOURCE_FONTS = {
    "solid": PACKAGE_ROOT / "webfonts" / "fa-solid-900.woff2",
    "brands": PACKAGE_ROOT / "webfonts" / "fa-brands-400.woff2",
}
OUTPUT_ROOT = ROOT / "assets" / "vendor" / "fontawesome"
OUTPUT_CSS = OUTPUT_ROOT / "css" / "subset.css"
OUTPUT_FONTS = {
    "solid": OUTPUT_ROOT / "webfonts" / "crc-icons-solid.woff2",
    "brands": OUTPUT_ROOT / "webfonts" / "crc-icons-brands.woff2",
}
OUTPUT_MANIFEST = OUTPUT_ROOT / "subset-manifest.json"
OUTPUT_LICENSE = OUTPUT_ROOT / "LICENSE.txt"
EXPECTED_PACKAGE_VERSION = "6.7.2"
EXPECTED_FONTTOOLS_VERSION = "4.62.1"
EXPECTED_NPM_INTEGRITY = "sha512-JUOtgFW6k9u4Y+xeIaEiLr3+cjoUPiAuLXoyKOJSia6Duzb7pq+A76P9ZdPDoAoxHdHzq6gE9/jKBGXlZT8FbA=="
EXPECTED_LICENSE_SHA256 = "9b914eae88817d63b576eab5aafde7068c7a1abae125d7cdfb034f1da43a9afc"
ICON_PATTERN = re.compile(r"\bfa-[a-z0-9-]+\b")
CLASS_PATTERN = re.compile(r"\bclass\s*=\s*([\"'])(.*?)\1", re.IGNORECASE | re.DOTALL)
SCRIPT_PATTERN = re.compile(r"<script\b[^>]*\bsrc\s*=\s*([\"'])(.*?)\1[^>]*>", re.IGNORECASE | re.DOTALL)
MAPPING_RULE_PATTERN = re.compile(r"([^{}]+)\{--fa:\"\\([0-9a-f]+)\"\}", re.IGNORECASE)
CUSTOM_FONT_NAMES = {
    "solid": "CRC Creator Icons Solid",
    "brands": "CRC Creator Icons Brands",
}

BASE_CSS = (
    '.fa,.fab,.fas{-moz-osx-font-smoothing:grayscale;'
    '-webkit-font-smoothing:antialiased;display:inline-block;font-style:normal;'
    'font-variant:normal;line-height:1;text-rendering:auto}'
    '.fa:before,.fab:before,.fas:before{content:var(--fa)}'
    '.fa,.fas{font-family:"CRC Creator Icons Solid";font-weight:900}'
    '.fab{font-family:"CRC Creator Icons Brands";font-weight:400}'
)
FONT_FACE_CSS = (
    '@font-face{font-family:"CRC Creator Icons Brands";font-style:normal;'
    'font-weight:400;font-display:swap;'
    'src:url(../webfonts/crc-icons-brands.woff2) format("woff2")}'
    '@font-face{font-family:"CRC Creator Icons Solid";font-style:normal;'
    'font-weight:900;font-display:swap;'
    'src:url(../webfonts/crc-icons-solid.woff2) format("woff2")}'
)
CSS_HEADER = (
    "/*!\n"
    " * Font Awesome Free 6.7.2 maintained-page subset - https://fontawesome.com\n"
    " * License - https://fontawesome.com/license/free "
    "(Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT)\n"
    " * Generated by scripts/subset-fontawesome.py; do not edit directly.\n"
    " */\n"
)


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def maintained_sources() -> tuple[list[Path], list[Path]]:
    sitemap_root = ET.parse(ROOT / "sitemap.xml").getroot()
    namespace = {"s": "http://www.sitemaps.org/schemas/sitemap/0.9"}
    files: list[Path] = []
    for node in sitemap_root.findall("s:url/s:loc", namespace):
        url_path = urlparse(node.text or "").path.lstrip("/")
        if not url_path:
            files.append(ROOT / "index.html")
        elif url_path.endswith("/"):
            files.append(ROOT / url_path / "index.html")
        else:
            files.append(ROOT / url_path)
    files.append(ROOT / "404.html")
    missing = [path for path in files if not path.is_file()]
    if missing:
        raise RuntimeError(f"Maintained page source missing: {missing[0].relative_to(ROOT)}")
    scripts: set[Path] = set()
    root_resolved = ROOT.resolve()
    for page in files:
        text = page.read_text(encoding="utf-8")
        for match in SCRIPT_PATTERN.finditer(text):
            parsed = urlparse(match.group(2))
            if parsed.scheme or parsed.netloc or not parsed.path:
                continue
            candidate = (ROOT / parsed.path.lstrip("/")) if parsed.path.startswith("/") else (page.parent / parsed.path)
            candidate = candidate.resolve()
            try:
                candidate.relative_to(root_resolved)
            except ValueError as error:
                raise RuntimeError(f"Maintained page script escapes the repository: {match.group(2)}") from error
            if not candidate.is_file():
                raise RuntimeError(f"Maintained page script missing: {candidate.relative_to(ROOT)}")
            scripts.add(candidate)
    return files, sorted(scripts)


def icon_usage(files: list[Path], known_brand_icons: set[str]) -> tuple[dict[str, set[str]], set[str]]:
    families = {"solid": set(), "brands": set()}
    all_icons: set[str] = set()
    icons_seen_in_classes: set[str] = set()

    for path in files:
        text = path.read_text(encoding="utf-8")
        all_icons.update(ICON_PATTERN.findall(text))
        for class_match in CLASS_PATTERN.finditer(text):
            classes = set(class_match.group(2).split())
            icons = classes & set(ICON_PATTERN.findall(class_match.group(2)))
            if not icons:
                continue
            icons_seen_in_classes.update(icons)
            family = "brands" if {"fab", "fa-brands"} & classes else "solid"
            families[family].update(icons)

    # Linked JavaScript can add icon names without an HTML family class. Use
    # the pinned upstream brands stylesheet to classify those names.
    for icon in all_icons - icons_seen_in_classes:
        family = "brands" if icon in known_brand_icons else "solid"
        families[family].add(icon)
    overlap = families["solid"] & families["brands"]
    if overlap:
        raise RuntimeError(f"Icon class used as both solid and brand: {sorted(overlap)}")
    return families, all_icons


def source_mappings(css: str) -> tuple[dict[str, tuple[str, int]], list[tuple[str, int]]]:
    by_class: dict[str, tuple[str, int]] = {}
    ordered_rules: list[tuple[str, int]] = []
    for match in MAPPING_RULE_PATTERN.finditer(css):
        selector = match.group(1)
        codepoint = int(match.group(2), 16)
        ordered_rules.append((selector, codepoint))
        for icon_class in ICON_PATTERN.findall(selector):
            by_class[icon_class] = (selector, codepoint)
    return by_class, ordered_rules


def build_css(all_icons: set[str], ordered_rules: list[tuple[str, int]]) -> bytes:
    selected_rules: list[str] = []
    for selector, codepoint in ordered_rules:
        if all_icons & set(ICON_PATTERN.findall(selector)):
            selected_rules.append(f'{selector}{{--fa:"\\{codepoint:x}"}}')
    return (CSS_HEADER + BASE_CSS + "".join(selected_rules) + FONT_FACE_CSS + "\n").encode("utf-8")


def rename_modified_font(font: TTFont, family: str) -> None:
    family_name = CUSTOM_FONT_NAMES[family]
    replacements = {
        1: family_name,
        2: "Regular",
        3: f"{family_name} 1.0",
        4: family_name,
        6: family_name.replace(" ", ""),
        16: family_name,
        17: "Regular",
    }
    for record in font["name"].names:
        replacement = replacements.get(record.nameID)
        if replacement is not None:
            record.string = replacement.encode(record.getEncoding())


def subset_font(source: Path, output: Path, codepoints: set[int], family: str) -> None:
    options = subset.Options()
    options.flavor = "woff2"
    options.hinting = False
    options.name_IDs = [0, 1, 2, 3, 4, 5, 6, 13, 14, 16, 17]
    options.name_languages = ["*"]
    options.name_legacy = False
    options.notdef_glyph = True
    options.notdef_outline = True
    options.recommended_glyphs = True

    font = TTFont(source, recalcTimestamp=False)
    subsetter = subset.Subsetter(options=options)
    subsetter.populate(unicodes=codepoints)
    subsetter.subset(font)
    rename_modified_font(font, family)
    font.flavor = "woff2"
    output.parent.mkdir(parents=True, exist_ok=True)
    font.save(output, reorderTables=False)

    rendered = TTFont(output, recalcTimestamp=False)
    rendered_codepoints = set(rendered.getBestCmap())
    if rendered_codepoints != codepoints:
        missing = codepoints - rendered_codepoints
        extra = rendered_codepoints - codepoints
        details = []
        if missing:
            details.append("missing " + ", ".join(f"U+{value:04X}" for value in sorted(missing)))
        if extra:
            details.append("unexpected " + ", ".join(f"U+{value:04X}" for value in sorted(extra)))
        raise RuntimeError(f"Subset font {output.name} cmap mismatch: {'; '.join(details)}")
    primary_name_ids = {1, 3, 4, 6, 16, 17}
    primary_names = [
        record.toUnicode()
        for record in rendered["name"].names
        if record.nameID in primary_name_ids
    ]
    if any("font awesome" in name.casefold() for name in primary_names):
        raise RuntimeError(f"Modified font {output.name} retains a reserved primary font name")


def manifest_for(
    pages: list[Path],
    scripts: list[Path],
    families: dict[str, set[str]],
    mappings: dict[str, tuple[str, int]],
    css_data: bytes,
    font_paths: dict[str, Path],
    license_path: Path,
) -> dict:
    family_entries = {}
    for family in ("solid", "brands"):
        data = font_paths[family].read_bytes()
        family_entries[family] = {
            "file": str(OUTPUT_FONTS[family].relative_to(ROOT)).replace("\\", "/"),
            "classes": sorted(families[family]),
            "unicodes": [f"U+{value:04X}" for value in sorted({mappings[name][1] for name in families[family]})],
            "cssFamily": CUSTOM_FONT_NAMES[family],
            "bytes": len(data),
            "sha256": sha256(data),
        }
    return {
        "source": {
            "package": "@fortawesome/fontawesome-free",
            "version": EXPECTED_PACKAGE_VERSION,
            "fontTools": EXPECTED_FONTTOOLS_VERSION,
            "license": "CC-BY-4.0 AND OFL-1.1 AND MIT",
        },
        "pages": [str(path.relative_to(ROOT)).replace("\\", "/") for path in pages],
        "scripts": [str(path.relative_to(ROOT)).replace("\\", "/") for path in scripts],
        "licenseFile": {
            "file": str(OUTPUT_LICENSE.relative_to(ROOT)).replace("\\", "/"),
            "bytes": license_path.stat().st_size,
            "sha256": sha256(license_path.read_bytes()),
        },
        "styles": {
            "file": str(OUTPUT_CSS.relative_to(ROOT)).replace("\\", "/"),
            "bytes": len(css_data),
            "sha256": sha256(css_data),
        },
        "families": family_entries,
        "totalFontBytes": sum(entry["bytes"] for entry in family_entries.values()),
    }


def build(destination: Path) -> tuple[bytes, dict, dict[str, Path]]:
    if not PACKAGE_JSON.is_file():
        raise RuntimeError("Run npm ci before generating Font Awesome assets")
    package = json.loads(PACKAGE_JSON.read_text(encoding="utf-8"))
    if package.get("version") != EXPECTED_PACKAGE_VERSION:
        raise RuntimeError(
            f"Expected Font Awesome {EXPECTED_PACKAGE_VERSION}, found {package.get('version')}"
        )
    if fonttools_version != EXPECTED_FONTTOOLS_VERSION:
        raise RuntimeError(
            f"Expected fontTools {EXPECTED_FONTTOOLS_VERSION}, found {fonttools_version}"
        )

    lock = json.loads((ROOT / "package-lock.json").read_text(encoding="utf-8"))
    locked_package = lock.get("packages", {}).get("node_modules/@fortawesome/fontawesome-free", {})
    if locked_package.get("integrity") != EXPECTED_NPM_INTEGRITY:
        raise RuntimeError("Pinned Font Awesome package integrity does not match the approved source")
    source_license = PACKAGE_ROOT / "LICENSE.txt"
    if sha256(source_license.read_bytes()) != EXPECTED_LICENSE_SHA256:
        raise RuntimeError("Pinned Font Awesome license does not match the approved upstream file")

    pages, scripts = maintained_sources()
    mappings, ordered_rules = source_mappings(SOURCE_CSS.read_text(encoding="utf-8"))
    brand_mappings, _ = source_mappings(SOURCE_BRANDS_CSS.read_text(encoding="utf-8"))
    families, all_icons = icon_usage([*pages, *scripts], set(brand_mappings))
    missing_mappings = all_icons - set(mappings)
    if missing_mappings:
        raise RuntimeError(f"Font Awesome CSS mapping missing: {sorted(missing_mappings)}")

    css_data = build_css(all_icons, ordered_rules)
    destination_css = destination / OUTPUT_CSS.relative_to(ROOT)
    destination_css.parent.mkdir(parents=True, exist_ok=True)
    destination_css.write_bytes(css_data)

    font_paths: dict[str, Path] = {}
    for family in ("solid", "brands"):
        output = destination / OUTPUT_FONTS[family].relative_to(ROOT)
        codepoints = {mappings[name][1] for name in families[family]}
        subset_font(SOURCE_FONTS[family], output, codepoints, family)
        font_paths[family] = output

    destination_license = destination / OUTPUT_LICENSE.relative_to(ROOT)
    destination_license.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(source_license, destination_license)
    manifest = manifest_for(pages, scripts, families, mappings, css_data, font_paths, destination_license)
    manifest_data = (json.dumps(manifest, indent=2) + "\n").encode("utf-8")
    destination_manifest = destination / OUTPUT_MANIFEST.relative_to(ROOT)
    destination_manifest.parent.mkdir(parents=True, exist_ok=True)
    destination_manifest.write_bytes(manifest_data)
    return manifest_data, manifest, font_paths


def check() -> int:
    with tempfile.TemporaryDirectory(prefix="crc-fontawesome-") as temp_dir:
        temp_root = Path(temp_dir)
        manifest_data, manifest, generated_fonts = build(temp_root)
        comparisons = [
            (temp_root / OUTPUT_CSS.relative_to(ROOT), OUTPUT_CSS),
            (temp_root / OUTPUT_MANIFEST.relative_to(ROOT), OUTPUT_MANIFEST),
            (temp_root / OUTPUT_LICENSE.relative_to(ROOT), OUTPUT_LICENSE),
            *[(generated_fonts[family], OUTPUT_FONTS[family]) for family in ("solid", "brands")],
        ]
        mismatches = []
        for generated, tracked in comparisons:
            if not tracked.is_file() or generated.read_bytes() != tracked.read_bytes():
                mismatches.append(str(tracked.relative_to(ROOT)).replace("\\", "/"))
        if mismatches:
            print("Font Awesome assets are stale: " + ", ".join(mismatches), file=sys.stderr)
            return 1
        print(
            "Font Awesome subset is reproducible: "
            f"{len(manifest['families']['solid']['classes'])} solid classes, "
            f"{len(manifest['families']['brands']['classes'])} brand classes, "
            f"{manifest['totalFontBytes']:,} font bytes."
        )
        return 0


def write() -> int:
    _, manifest, generated_fonts = build(ROOT)
    print(
        "Generated Font Awesome subset: "
        f"{len(manifest['families']['solid']['classes'])} solid classes, "
        f"{len(manifest['families']['brands']['classes'])} brand classes, "
        f"{manifest['totalFontBytes']:,} font bytes."
    )
    return 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="verify tracked output byte-for-byte")
    args = parser.parse_args()
    raise SystemExit(check() if args.check else write())
